server:
  port: 8080

spring:
  application:
    name: Xiangqi
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  config:
    import: env.properties
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: 10000 # in second
  refreshable-duration: 36000 # in seconds

